# Generated by Django 4.2.6 on 2023-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='tax_id',
            field=models.CharField(blank=True, null=True, verbose_name='ИНН'),
        ),
    ]
