# Generated by Django 4.2.6 on 2023-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_change_additional_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='status',
            field=models.CharField(choices=[('needs_moderation', 'Требует модерации'), ('moderated', 'Промодерирован на СВХ'), ('reserved', 'Забронирован'), ('paid', 'Оплачен'), ('issued', 'Выдан'), ('in_transit', 'В пути'), ('ready', 'Готов к выдаче')], default='needs_moderation', max_length=30, verbose_name='Статус'),
        ),
    ]
