# Generated by Django 4.2.6 on 2023-11-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_init'),
        ('auto', '0005_change_enums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='seller.seller', verbose_name='Продавец'),
        ),
    ]
