# Generated by Django 4.2.6 on 2023-11-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_change_enums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.AddField(
            model_name='equipment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_equipment', to='auto.car', verbose_name='Модель авто'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_offers', to='auto.equipment', verbose_name='Комплектация'),
        ),
    ]
