# Generated by Django 4.2.6 on 2023-11-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_change_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_offers', to='auto.equipment', verbose_name='Комплектация'),
        ),
    ]
