# Generated by Django 4.2.6 on 2023-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_replace_one2one_to_fk'),
        ('auto', '0007_change_eq_offer'),
    ]

    operations = [
    ]
