# Generated by Django 4.2.6 on 2023-11-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_merge_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Тип КПП', 'verbose_name_plural': 'Тип КПП'},
        ),
        migrations.AlterField(
            model_name='car',
            name='front_brakes',
            field=models.BooleanField(default=False, help_text='(без галочки ободные, с галочкой дисковые)', verbose_name='Передние тормоза'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rear_brakes',
            field=models.BooleanField(default=False, help_text='(без галочки ободные, с галочкой дисковые)', verbose_name='Задние тормоза'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_transmission_type', to='auto.transmission', verbose_name='Тип КПП'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='front_brakes',
            field=models.BooleanField(default=False, help_text='(без галочки ободные, с галочкой дисковые)', verbose_name='Передние тормоза'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rear_brakes',
            field=models.BooleanField(default=False, help_text='(без галочки ободные, с галочкой дисковые)', verbose_name='Задние тормоза'),
        ),
    ]
