# Generated by Django 4.2.6 on 2023-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_otp_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='CMR',
            field=models.FileField(blank=True, null=True, upload_to='cmr_files/', verbose_name='CMR'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract_files/', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='customs_inspection_report',
            field=models.FileField(blank=True, null=True, upload_to='customs_inspection_report_files/', verbose_name='Акт таможенного осмотра'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='handover_act',
            field=models.FileField(blank=True, null=True, upload_to='handover_act_files/', verbose_name='Акт приема - передачи'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice_files/', verbose_name='Инвойс'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='packing_list',
            field=models.FileField(blank=True, null=True, upload_to='packing_list_files/', verbose_name='Упаковочный лист'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='seller_proxy_to_broker',
            field=models.FileField(blank=True, null=True, upload_to='seller_proxy_to_broker_files/', verbose_name='Доверенность продавца на брокера'),
        ),
    ]
