# Generated by Django 4.2.6 on 2023-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_null_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость со скидкой'),
        ),
    ]
