# Generated by Django 4.2.6 on 2023-11-22 09:27

import django.core.validators
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_remove_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='state',
            field=django_fsm.FSMField(choices=[('on_check', 'На проверке'), ('approved', 'Подтвержден'), ('rejected', 'Отклонено')], default='on_check', max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Лошадиные силы'),
        ),
    ]
