# Generated by Django 4.2.6 on 2023-12-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_add_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin_offer', to='auto.offer', verbose_name='Предложение'),
        ),
    ]
