# Generated by Django 4.2.6 on 2023-12-12 20:16

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_change_on_delete_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='status',
            field=django_fsm.FSMField(choices=[('needs_moderation', 'Требует модерации'), ('moderated', 'Промодерирован на СВХ'), ('reserved', 'Забронирован'), ('paid', 'Оплачен'), ('issued', 'Выдан'), ('in_transit', 'В пути'), ('ready', 'Готов к выдаче')], default='needs_moderation', max_length=30, verbose_name='Статус'),
        ),
    ]
