# Generated by Django 4.2.6 on 2023-12-14 00:31

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_change_field_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='unique_car',
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=django_fsm.FSMField(choices=[('on_check', 'На проверке'), ('approved', 'Подтвержден'), ('rejected', 'Отклонено')], default='on_check', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('brand', 'model', 'body_type', 'color', 'engine_type', 'engine_volume', 'transmission_type', 'drive_type', 'assembly_country', 'manufacturing_year', 'steering_side', 'status'), name='unique_car'),
        ),
    ]
