# Generated by Django 4.2.6 on 2023-12-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0015_add_status_in_car_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carbrand',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_brand_name'),
        ),
        migrations.AddConstraint(
            model_name='carcolor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_color_name'),
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_brand_model_name'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_country_name'),
        ),
        migrations.AddConstraint(
            model_name='drive',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_drive_name'),
        ),
        migrations.AddConstraint(
            model_name='enginetype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_engine_type_name'),
        ),
        migrations.AddConstraint(
            model_name='enginevolume',
            constraint=models.UniqueConstraint(fields=('volume',), name='unique_engine_volume'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('name', 'car'), name='unique_car_equipment_name'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('name', 'subsection'), name='unique_subsection_feature_name'),
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('name', 'equipment'), name='unique_equipment_subsection_name'),
        ),
        migrations.AddConstraint(
            model_name='transmission',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_transmission_name'),
        ),
    ]
