from app.conf.environ import env


SBERPAY_URL = env("SBERPAY_URL")
SBERPAY_USERNAME = env("SBERPAY_USERNAME")
SBERPAY_PASSWORD = env("SBERPAY_PASSWORD")
PAYMENT_PART_AMOUNT = env("PAYMENT_PART_AMOUNT")
PAYMENT_GW_RETURN_URL = env("PAYMENT_GW_RETURN_URL")
